### ISSUE TITLE
Not do anything

### ISSUE THREAD

**Issue by KicsiMedve** [amoxu/Baofeng-UV-5RM-5RH-RE#2]
Hi!
My device is 5RHL v01. 
Can i downrange somehow to 0.7 firmware?

**Comment by amoxu** [comment]
Hello,

Sorry, I have not meet anyone released the v0.7 firmware package in groups or community channels, so I cannot give you help at the moment.

According to other feedbacks I received, it seems that if your 5RH is factory-loaded with a firmware version lower than v0.9, which may used a different hardware design than this project.

If the description on the product page is different from 5RM or 5RH (M version), for example, the 5RHL you mentioned may be another design using a different RF solution, So upgradeing the firmware provided in this project will result in the inability to perform RF operations. 

I will wait until I have the opportunity to buy this version of hardware in the future and I will try to do research on it.

73 
Amo 
BD4VOW

**Comment by KicsiMedve** [comment]
Can you publish a backup software?
I try to find an another device to make a backup.

**Comment by amoxu** [comment]
Because of writing Flash depends on the original Bootloader, and the storage principle of Flash requires erasing the Flash in the area to be written before writing, so in theory there is currently no effective & affordable method to directly read the whole factory firmware from device.

For more details, please refer to [3.Bootloader Dumping](https://github.com/amoxu/Baofeng-UV-5RM-5RH-RE?tab=readme-ov-file#3-bootloader-binary-dumping)

I'm very sorry that I can't help you at the moment.

**Comment by amoxu** [comment]
> Hi! My device is 5RHL v01. Can i downrange somehow to 0.7 firmware?

Hi!

Please try this file [5RH_AT1846S_V0.07_FangtiBlueBG_230918.BF](https://github.com/amoxu/Baofeng-UV-5RM-5RH-RE/raw/main/factory_firmware/L_AT1846S/5RH_AT1846S_V0.07_FangtiBlueBG_230918.BF).
Good luck.

**Comment by KicsiMedve** [comment]
> > Hi! My device is 5RHL v01. Can i downrange somehow to 0.7 firmware?
> 
> Hi!
> 
> Please try this file [5RH_AT1846S_V0.07_FangtiBlueBG_230918.BF](https://github.com/amoxu/Baofeng-UV-5RM-5RH-RE/raw/main/factory_firmware/L_AT1846S/5RH_AT1846S_V0.07_FangtiBlueBG_230918.BF).
> Good luck.

Hi! 

It works! 

Thank you!
